#!/usr/bin/bash
echo ' ________________'
echo '< find some file >'
echo ' ----------------'
echo '        \   ^__^'
echo '        \  (oo)\_______'
echo '           (__)\       )\/\'
echo '               ||----w |'
echo '               ||     ||'



# 定义脚本的使用方式
usage() {
	echo "作用:自动提取文件中存在的敏感信息"
	echo ""
	echo "Usage(使用方法): $0 -l <directory_path>"
	echo "参考了findsomething中的正则"
    exit 1
}

# 检查参数
if [[ "$#" -ne 2 || "$1" != "-l" ]]; then
    usage
fi

file="$2"

# 检查文件夹是否存在
if [[ ! -d "$file" ]]; then
    echo "Error: The specified directory does not exist: $file"
    exit 1
fi


clear

echo "------------url---------------"
url=$(find $file -type f -exec grep -oP '\bhttps?://\S+\b' {} + | grep -vE '\.(jpg|jpeg|png|gif|bmp|svg|webp|svg)' |grep -vE '\/jpg|jpeg|png|gif|bmp|svg|webp|svg' | sort -u | grep -vE 'qq\.|\.org|\.qq|\.weixin|weixin\.')
echo "$url" | sort -u 


echo "--------------domain---------"
domain=$(echo "$url" | awk -F'://' '{print $2}' | awk -F'/' '{print $1}')
echo "$domain" |sort -u

echo "------------IP---------------"
ip() {
find $file -type f -exec grep -oP '(127\.0\.0\.1|localhost|10\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}|172\.(1[6-9]|2[0-9]|3[01])\.[0-9]{1,3}\.[0-9]{1,3}|192\.168\.[0-9]{1,3}\.[0-9]{1,3})' {} +
find $file -type f -exec grep -E "'\"\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\"|\'\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}\'" {} +
find $file -type f -exec grep -E "'\"\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}:\d{1,5}\"|\'\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}:\d{1,5}\'" {} +
}
ip |sort -u

echo -e "\n \n"

echo "================API====================="
#将变量中的值存放到临时文件中
touch /tmp/.api_var
echo "$file" > /tmp/.api_var

echo "------------api in url---------------"
find $file -type f -exec grep -oP 'https?://\S+' {} + | grep -vE '\.(jpg|jpeg|png|gif|bmp|svg|webp)' | grep -i 'api' | sort -u | grep -vE 'qq\.|\.org|\.qq|\.weixin|weixin\.'

#使用python脚本

python3 find_apipath.py > apipath.txt
cat apipath.txt |sort -u|grep -v -e '\.json' -e '\.wxml'|grep -v '^https'|grep -v '^http' > apipath.txt
cat apipath.txt
rm /tmp/.api_var


echo -e "\n \n"
echo "-----------Js---------------"
find $file -name "*.js" -type f

echo "------------json--------------"
find $file -name "*.json" -type f |sort -u |grep -v "miniprogram_npm"

echo "-------------config---------------"
find $file -type f -name "*config*"

echo -e "\n \n \n"
echo "----------身份证--------------"
find $file -type f -exec grep -oP '\b[1-9]\d{5}(18|19|20)\d{2}(0[1-9]|1[0-2])(0[1-9]|[12]\d|3[01])\d{3}[\dXx]\b' {} + | sort -u 

echo "------------疑似手机号？phone---------------"
find $file -type f -exec grep -oP '\b\d{11}\b' {} + | sort -u 

echo "------------邮箱---------------"
find $file -type f -exec grep -oEh '\b[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}\b' {} + | sort -u


echo -e "\n \n \n"
echo "-----------小程序敏感信息提取----------------"
echo "-------疑似acesstoken----"
aktoken() {
find $file -type f -exec grep -E 'access.*?key.*?=|access.*?key.*?:|token.*?key.*?=|token.*?key.*?:' {} + |sort -u
find $file -type f -exec grep -E 'access_key|access_token|client_secret' {} + |sort -u
}
aktoken |sort -u

echo -e "\n"
echo "----------------检测可能存在的AccessKeyId&AccessKeySecret----------------"
echo "正则参考了hae以及ApkAnalyser"
# 确保 $file 变量被设置为一个目录路径  
if [ ! -d "$file" ]; then  
    exit 1  
fi  
  
# 搜索匹配AccessKeyId的文件  
search_access_key_id() {  
    local directory="$1"  
    find "$directory" -type f -exec perl -0777 -ne '  
        BEGIN { print "---AccessKeyId匹配的文件---\n" }  
        if (/^(?=.*[A-Z])(?=.*[a-z])(?=.*[0-9]).{24}$/) {  
            print "文件: $ARGV 匹配到AccessKeyId！！！\n";  
            exit 0; # 找到匹配后退出，避免处理更多文件  
        }  
    ' {} +  
}  

# 检查字符串是否匹配AccessKeySecret的正则表达式  
check_access_key_secret() {  
    local string="$1"  
    echo "$string" | awk 'length($0) == 30 &&  
        match($0, /[A-Z]/) &&  
        match($0, /[a-z]/) &&  
        match($0, /[0-9]/) {  
            print  
        }'  
}  
  
# 调用函数并打印结果  
search_access_key_id "$file"  
  
# 假设这里有一个 AccessKeySecret 字符串需要检查  
access_key_secret="YourAccessKeySecretStringToCheck"  
access_key_secret_result=$(check_access_key_secret "$access_key_secret")  
  
echo "----AccessKeySecret----"  
if [ -n "$access_key_secret_result" ]; then  
    echo "$access_key_secret_result 匹配 AccessKeySecret 的正则表达式"  
else  
    echo "未找到匹配的 AccessKeySecret"  
fi

#关键字匹配
secret() {
find $file -type f -exec grep -iE '[*]secret[id|key].*?=|secret[id|key].*?:".*?"' {} +
find $file -type f -exec grep -iE 'secret[id|key].*?=|secret[id|key].*?:".*?"' {} +
find $file -type f -exec grep -iE 'secret(id|key).*?=.*?".*?"|secret(id|key).*?:.*?".*?"' {} +
find $file -type f -exec grep -iE 'appsecret|app_secret' {} +
find $file -type f -exec grep -iE 'Accesskey|Accesskeysecret|ossAccessid' {} + |sort -u
}
secret=$(secret)
echo "$secret" | sort -u

echo -e "\n"
echo "--------corpid--------------"
# 搜索并输出包含特定字符串的文件列表
find_corpid() {
	find $file -type f -exec grep -iE '(wechatSecretKey|wechatAppId|corpid|SecretKey|Secretid|AppId)' {} + | sort -u
	
}

# 调用函数获取结果，并存入变量
corpid=$(find_corpid)

# 输出结果
echo "$corpid"

echo -e "\n"
echo "-------------oss key---------------"
find $file -type f -exec grep -E '\b((Ac[Kk]eyS[Ee]cret)|(Ac[Kk]ey[Ii][Dd])|(A[Cc]cess_[Kk]ey)|(A[Cc]cess_[Ss]ecret)|(A[Cc]cess_[Ii][Dd])|(S[Ss]ecret_[Kk]ey))\b' {} +

echo -e "\n"
echo "------------Aliyun oss--------------"
find $file -type f -exec grep -E '[[:alnum:]_.-]+\.oss\.aliyuncs\.com' {} +

echo -e "\n \n"
echo "------------hash------------------"
ak() {
find $file -type f -exec grep -oP 'LTAI[A-Za-z0-9]{12,20}' {} +
find $file -type f -exec grep -oP 'AKID[A-Za-z0-9]{13,20}' {} +
find $file -type f -exec grep -oP 'AK[\w\W]{10,62}' {} +
find $file -type f -exec grep -oP 'AK[A-Za-z0-9]{10,40}' {} +
find $file -type f -exec grep -oP 'JDC_[A-Z0-9]{28,32}' {} +
find $file -type f -exec grep -oP 'AKLT[a-zA-Z0-9-_]{0,252}' {} +
find $file -type f -exec grep -oP 'UC[A-Za-z0-9]{10,40}' {} +
find $file -type f -exec grep -oP 'QY[A-Za-z0-9]{10,40}' {} +
find $file -type f -exec grep -oP 'AKLT[a-zA-Z0-9-_]{16,28}' {} +
find $file -type f -exec grep -oP 'LTC[A-Za-z0-9]{10,60}' {} +
find $file -type f -exec grep -oP 'YD[A-Za-z0-9]{10,60}' {} +
find $file -type f -exec grep -oP 'CTC[A-Za-z0-9]{10,60}' {} +
find $file -type f -exec grep -oP 'YYT[A-Za-z0-9]{10,60}' {} +
find $file -type f -exec grep -oP 'YY[A-Za-z0-9]{10,40}' {} +
find $file -type f -exec grep -oP 'CI[A-Za-z0-9]{10,40}' {} +
find $file -type f -exec grep -oP 'gcore[A-Za-z0-9]{10,30}' {} +
}
ak | sort -u 

echo "----------hash提取(16位/32位)--------"
# 假设 $file 是一个目录路径  
hashlist=()  
  
# 使用 find 命令递归地查找 $file 目录下的所有文件，并逐行读取内容  
while IFS= read -r file; do  
    # 只处理普通文件  
    if [[ -f "$file" ]]; then  
        while IFS= read -r line; do  
            # 检查字符串长度是否为 16 或 32  
            if [[ ${#line} -eq 16 || ${#line} -eq 32 ]]; then  
                # 使用正则表达式检查字符串是否只包含小写字母和数字  
                if [[ $line =~ ^[a-z0-9]+$ ]]; then  
                    # 将字符串添加到 hashlist 数组中，使用关联数组自动去重  
                    declare -A unique_hashes  
                    unique_hashes["$line"]=1  
                fi  
            fi  
        done < "$file"  
    fi  
done < <(find "$file" -type f)  
  
# 获取去重后的哈希值列表  
hashes=()  
for hash in "${!unique_hashes[@]}"; do  
    hashes+=("$hash")  
done  
  
# 如果找到至少一个哈希值，则输出到 hash.txt 文件  
#if [[ ${#hashes[@]} -gt 0 ]]; then  
    # 确保 hash.txt 文件在正确的目录下，这里假设在当前目录  
   # hashfile="hash.txt"  
  
    # 将去重后的哈希值列表写入 hash.txt 文件  
   # printf '%s\n' "${hashes[@]}" > "$hashfile"  
#fi  
  
# 如果需要，打印出找到的哈希值（可选）  
if [[ ${#hashes[@]} -gt 0 ]]; then  
    echo "Found hashes:"  
    for hash in "${hashes[@]}"; do  
        echo "$hash"  
    done  

fi


echo ' ________________'
echo '< find some file Over!>'
echo ' ----------------'
echo '        \   ^__^'
echo '        \  (oo)\_______'
echo '           (__)\       )\/\'
echo '               ||----w |'
echo '               ||     ||'

